server:
  port: 9000
spring:
  application:
    name: login-server
  cloud:
    nacos:
      discovery:
        server-addr: 120.48.26.152:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.48.26.152:12345/lcoil?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 180000
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
  elasticsearch:
    rest:
      username: elastic
      password: 123456
      uris: 120.48.26.152:9200
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*=/com/lcoil/mapper/*.xml
  type-aliases-package: org.example.mapper
